In [1]:
import pandas as pd

In [2]:
# Load csv file

data= pd.read_csv('IDS_CSV/IDSData.csv')
data

,Country Name,Country Code,Indicator Name,Indicator Code,1970,1971,1972,1973,1974,1975,...,2018,2019,2020,2021,2022,2023,2024,2025,2026,Unnamed: 61
0,Afghanistan,AFG,Average grace period on new external debt comm...,DT.GPA.DPPG,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,Average grace period on new external debt comm...,DT.GPA.OFFT,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,Average grace period on new external debt comm...,DT.GPA.PRVT,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,Average grant element on new external debt com...,DT.GRE.DPPG,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,Average grant element on new external debt com...,DT.GRE.OFFT,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67090,Upper middle income,UMC,"Undisbursed external debt, official creditors ...",DT.UND.OFFT.CD,5.829034e+09,6.955818e+09,8.588872e+09,1.048724e+10,1.299651e+10,1.380461e+10,...,1.227277e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67091,Upper middle income,UMC,"Undisbursed external debt, private creditors (...",DT.UND.PRVT.CD,2.058917e+09,3.014798e+09,3.159936e+09,4.354387e+09,6.499489e+09,1.005456e+10,...,2.755091e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67092,Upper middle income,UMC,"Undisbursed external debt, total (UND, current...",DT.UND.DPPG.CD,7.887951e+09,9.970616e+09,1.174881e+10,1.484163e+10,1.949600e+10,2.385917e+10,...,1.502786e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67093,Upper middle income,UMC,"Use of IMF credit (DOD, current US$)",DT.DOD.DIMF.CD,2.377000e+08,3.026072e+08,4.118065e+08,4.218765e+08,4.770626e+08,1.018919e+09,...,8.398442e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67094,Upper middle income,UMC,"Use of IMF credit, SDR allocations (DOD, curre...",DT.DOD.DSDR.CD,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,5.121887e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67095 entries, 0 to 67094
Data columns (total 62 columns):
Country Name      67095 non-null object
Country Code      67095 non-null object
Indicator Name    67095 non-null object
Indicator Code    67095 non-null object
1970              65536 non-null float64
1971              65559 non-null float64
1972              65578 non-null float64
1973              65592 non-null float64
1974              65677 non-null float64
1975              65791 non-null float64
1976              65930 non-null float64
1977              66123 non-null float64
1978              66182 non-null float64
1979              66211 non-null float64
1980              66262 non-null float64
1981              66324 non-null float64
1982              66377 non-null float64
1983              66378 non-null float64
1984              66407 non-null float64
1985              66435 non-null float64
1986              66451 non-null float64
1987              66457 non-null float64
1988              66462 non-null float64
1989              66486 non-null float64
1990              66496 non-null float64
1991              66511 non-null float64
1992              66548 non-null float64
1993              66617 non-null float64
1994              66657 non-null float64
1995              66685 non-null float64
1996              66701 non-null float64
1997              66739 non-null float64
1998              66726 non-null float64
1999              66734 non-null float64
2000              66747 non-null float64
2001              66756 non-null float64
2002              66763 non-null float64
2003              66779 non-null float64
2004              66805 non-null float64
2005              66818 non-null float64
2006              66844 non-null float64
2007              66870 non-null float64
2008              66887 non-null float64
2009              66894 non-null float64
2010              66894 non-null float64
2011              66886 non-null float64
2012              66886 non-null float64
2013              66894 non-null float64
2014              66891 non-null float64
2015              66888 non-null float64
2016              66999 non-null float64
2017              66960 non-null float64
2018              66807 non-null float64
2019              3645 non-null float64
2020              3645 non-null float64
2021              3645 non-null float64
2022              3645 non-null float64
2023              3645 non-null float64
2024              3645 non-null float64
2025              3645 non-null float64
2026              3645 non-null float64
Unnamed: 61       0 non-null float64
dtypes: float64(58), object(4)
memory usage: 31.7+ MB

In [4]:
# Looking into data for null values

data.isnull().sum()

Country Name          0
Country Code          0
Indicator Name        0
Indicator Code        0
1970               1559
                  ...
2023              63450
2024              63450
2025              63450
2026              63450
Unnamed: 61       67095
Length: 62, dtype: int64

In [5]:
# Renaming columns for database
data = data.rename(columns={'Country Name': 'country_name',
                           'Country Code':'country_code',
                           'Indicator Name': 'indicator_name',
                           'Indicator Code': 'indicator_code'})
data

,country_name,country_code,indicator_name,indicator_code,1970,1971,1972,1973,1974,1975,...,2018,2019,2020,2021,2022,2023,2024,2025,2026,Unnamed: 61
0,Afghanistan,AFG,Average grace period on new external debt comm...,DT.GPA.DPPG,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,Average grace period on new external debt comm...,DT.GPA.OFFT,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,Average grace period on new external debt comm...,DT.GPA.PRVT,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,Average grant element on new external debt com...,DT.GRE.DPPG,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,Average grant element on new external debt com...,DT.GRE.OFFT,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67090,Upper middle income,UMC,"Undisbursed external debt, official creditors ...",DT.UND.OFFT.CD,5.829034e+09,6.955818e+09,8.588872e+09,1.048724e+10,1.299651e+10,1.380461e+10,...,1.227277e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67091,Upper middle income,UMC,"Undisbursed external debt, private creditors (...",DT.UND.PRVT.CD,2.058917e+09,3.014798e+09,3.159936e+09,4.354387e+09,6.499489e+09,1.005456e+10,...,2.755091e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67092,Upper middle income,UMC,"Undisbursed external debt, total (UND, current...",DT.UND.DPPG.CD,7.887951e+09,9.970616e+09,1.174881e+10,1.484163e+10,1.949600e+10,2.385917e+10,...,1.502786e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67093,Upper middle income,UMC,"Use of IMF credit (DOD, current US$)",DT.DOD.DIMF.CD,2.377000e+08,3.026072e+08,4.118065e+08,4.218765e+08,4.770626e+08,1.018919e+09,...,8.398442e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67094,Upper middle income,UMC,"Use of IMF credit, SDR allocations (DOD, curre...",DT.DOD.DSDR.CD,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,5.121887e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# #Save into new csv file

# data.to_csv('data/international_debt.csv')